/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:ad087e9e-2e32-404f-a891-f50b9edc61ad",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_i6qvnhqAl",
    "aws_user_pools_web_client_id": "7fdm6mvh9n6lvcn38qjv4e5igp",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://veiqwojvmrah3d5rb6jcs7w7ey.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
